# SwiftLint Configuration for MindBuddy iOS

# Included paths
included:
  - mindbuddy

# Excluded paths
excluded:
  - mindbuddy/Pods
  - mindbuddy/DerivedData
  - mindbuddy/build

# Rules configuration
opt_in_rules:
  - array_init
  - closure_spacing
  - empty_count
  - explicit_init
  - force_unwrapping
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - unused_optional_binding

disabled_rules:
  - trailing_whitespace # Handled by Xcode
  - line_length # Sometimes needed for readability

# Custom rule configurations
line_length:
  warning: 120
  error: 140

function_body_length:
  warning: 50
  error: 80

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y

force_cast: error
force_try: error
force_unwrapping: warning

# Custom rules
custom_rules:
  no_print_in_production:
    name: "No Print in Production"
    regex: '(?<!#if DEBUG\n)print\('
    message: "Print statements should only be used in DEBUG builds"
    severity: error
    
  secure_logging:
    name: "Secure Logging"
    regex: 'print.*(?:token|password|secret|key|credential)'
    message: "Avoid logging sensitive information"
    severity: error